# Generated by Django 4.2.7 on 2025-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des',
            field=models.TextField(blank=True, help_text='Description of the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=models.TextField(blank=True, help_text='overview of the product', null=True),
        ),
    ]
