# Generated by Django 4.2.7 on 2025-01-31 14:41

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_product_des_alter_product_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Text'),
        ),
    ]
