# Generated by Django 4.2.7 on 2025-01-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcart', '0003_checkout_payment_method_paidorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
