# Generated by Django 4.2.7 on 2025-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherimages',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
